Lesson 4 closures
EugeneBaichuk/js-home-tasks-Baichuk pull request #6
Opened 2022-02-13 17:57 UTC by EugeneBaichuk

2022-02-17 16:36 UTC, instinct-it-academy requested changes
Добрый вечер, доработайте пожалуйста вторую задачу. Обратите внимание на комментарии.

2022-02-17 16:36 UTC, instinct-it-academy commented on task1.js
> +validateForms(rowNum, 'Введите количество ячеек в строке');
если сделали функцию валидации, то было бы хорошо если бы она только возвращала true/false, остальное происходило бы за её рамками

2022-02-17 16:36 UTC, instinct-it-academy commented on task1.js
> +}
было бы хорошо объединить это в одну функцию, либо использовать одну внутри другой т.к. использовать отдельно, достаточно "неожиданно" будет для данной задачи

2022-02-17 16:36 UTC, instinct-it-academy commented on task2.js
> +    obj.className = obj.className.replace(cls, '').trim();
на сколько вижу trim справится с пробелами вначале и в конце, что будет с пробелами внутри строки? они останутся, доработайте пожалуйста данный момент. Например возьмите что-то такое 
`className: 'open aaa menu menu ddd menu menu'`

2022-02-20 04:23 UTC, EugeneBaichuk commented on task1.js
> +validateForms(rowNum, 'Введите количество ячеек в строке');
сделал вообще без функции, так как в данном случае из-за использования promt, как я понимаю, функция должна возвращать три варианта, true - получаем значение, false - повторно выводим promt, null - отмена, повторно форму не выводим. Вносить все три значения в функцию, чтобы получить true/false/null, а потом каждое описывать вне функции показалось мне нерациональным.

2022-02-20 04:23 UTC, EugeneBaichuk commented on task1.js
> +}
сделал 2 варианта

2022-02-20 04:23 UTC, EugeneBaichuk commented on task2.js
> +    obj.className = obj.className.replace(cls, '').trim();
переделано

2022-02-26 21:10 UTC, instinct-it-academy approved these changes

2022-02-26 21:10 UTC, merged